source 'https://rubygems.org'

gem 'rspec'
gem 'airborne'
gem 'watir-webdriver'
gem 'watir-rspec'
gem 'rake'
gem 'rspec-rerun'
gem 'pony'
gem 'slack-notifier'
gem 'multi_json'
gem 'thor'
gem 'open_uri_redirections'
gem 'rspec-retry'
gem 'webdriver-user-agent'